In [1]:
import pandas as pd

In [29]:
df = pd.read_csv('./sample/sales.csv')

df_level_1 = pd.read_csv('./sample/clusters_level_1.csv')

df_level_0 = pd.read_csv('./sample/clusters_level_0.csv')

In [15]:
df = df[df['store_id'] >= 4]

In [23]:
df_level_0[df_level_0['cluster_id'] == 5]

    store_id  product_id  cluster_id
48         5           1           5
49         5           2           5
50         5           3           5
51         5           4           5
52         5           5           5
53         5           6           5
60         6           1           5
61         6           2           5
62         6           3           5
63         6           4           5
64         6           5           5
65         6           6           5

In [28]:
df[(df['store_id'] >= 5) & (df['store_id'] <7)]['sales'].sum()

2132

In [45]:
df2 = df.groupby(['store_id', 'product_id'], as_index=False).sum()

In [58]:
df3 = pd.merge(df2, df_level_0, on=['store_id','product_id'])

In [67]:
df4 = pd.merge(df3, df_level_1, on=['store_id','product_id']).rename(columns={'cluster_id_x': 'level0', 'cluster_id_y': 'level1'})

In [85]:
clusters_ids = df4['level0'].unique().tolist() + df4['level1'].unique().tolist()

In [112]:
robustness_l0 = {}
robustness_l1 = {}

for cl in clusters_ids:
    robustness_l0[cl] = is_score_enough_for(df4[df4['level0'] == cl])
    robustness_l1[cl] = is_score_enough_for(df4[df4['level1'] == cl])

In [156]:
df4['robustness_l0'] = df4.apply (lambda row: store_robutness(row['level0'], robustness_l0), axis=1)

df4['robustness_l1'] = df4.apply (lambda row: store_robutness(row['level1'], robustness_l1), axis=1)

1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
1, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
2, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
3, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return False
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
4, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
5, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
6, {1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}
return True
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
7, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return False
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True
8, {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}
return True

In [149]:
df4 = df4.drop(columns=['robustness_l0', 'robustness_l1'])

In [124]:
robustness_l0

{1: False, 2: False, 3: False, 4: True, 5: True, 6: True, 7: False, 8: False}

In [125]:
robustness_l1

{1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False, 8: True}

In [155]:
def store_robustness(row_level, scores: list):
    return scores[row_level]

In [154]:
df4

    store_id  product_id  sales  level0  level1  robustness_l0  robustness_l1
0          1           1      4       1       7          False          False
1          1           2      4       1       7          False          False
2          1           3      5       1       7          False          False
3          1           4      6       1       7          False          False
4          1           5      6       1       7          False          False
..       ...         ...    ...     ...     ...            ...            ...
67         6           8     98       6       8           True           True
68         6           9    100       6       8           True           True
69         6          10    101       6       8           True           True
70         6          11    102       6       8           True           True
71         6          12    103       6       8           True           True

[72 rows x 7 columns]

In [ ]:
df4['robust'] = df4.apply (lambda row: cluster_df(row), axis=1)

In [108]:
def is_score_enough_for(cluster_df):
    return cluster_df['sales'].sum() >= 500

In [52]:
df2.shape

(72, 3)

In [56]:
df_level_0

    store_id  product_id  cluster_id
0          1           1           1
1          1           2           1
2          1           3           1
3          1           4           1
4          1           5           1
..       ...         ...         ...
67         6           8           6
68         6           9           6
69         6          10           6
70         6          11           6
71         6          12           6

[72 rows x 3 columns]

In [ ]:
pd.to_pickle(df)